Adding 'date posted' field to 'Post' model
beyond-io/PicATrip pull request #145
Opened 2021-05-17 16:17 UTC by Shoval-Ovadia

- Adding 'date posted' field - Post/models.py, Post/migrations/0001_initial.py and commenting_system/migrations/0001_initial.py modified.
- Ordering the posts at 'post list' from the newest to the oldest - Post/views.py modified.

closes #143 
closes #144

2021-05-17 20:45 UTC, nadavspinco approved these changes
LGTM. I suggest we will add this file to the show post details page and on the post list(on other PR)

2021-05-18 12:58 UTC, maayanhd requested changes
Maybe just add test to the field in this style- https://devblog.kogan.com/blog/testing-auto-now-datetime-fields-in-django
You can also add an update time in case the update post PR will be merged on time if you'd like

2021-05-18 20:44 UTC, Yarboa approved these changes

2021-05-19 13:03 UTC, Yarboa approved these changes

2021-05-19 13:03 UTC, merged